# Generated by Django 2.0.2 on 2020-06-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
