# Generated by Django 2.0.2 on 2020-06-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200614_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status post', 'verbose_name_plural': 'Status posts'},
        ),
    ]
